name: DevOps Environment Setup Test

on:
  push:
  pull_request:

jobs:
  test-devops-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Make scripts executable
        run: chmod +x dev-env/bootstrap.sh dev-env/install/*.sh

      - name: Run bootstrap
        run: ./dev-env/bootstrap.sh

      - name: Verify tools
        run: |
          kubectl version --client
          terraform version
          helm version
          go version
          python3 --version
          nvim --version

      - name: Test Neovim config
        run: nvim --headless "+qa"
